const GAMES = {

  // ─────────────────────────────────────────────
  // SECTION 1: BEST-LOOKING / SMOOTHEST FIRST
  // ─────────────────────────────────────────────
  byVisual: [
    {
      id: "botw",
      title: "Breath of the Wild",
      year: 2017,
      tier: "Tier 1 — Best Looking, Runs Great",
      tierClass: "tier1",
      platform: "Wii U / Switch",
      emulator: "Cemu (Wii U version — recommended)",
      yourPC: "✅ Runs great",
      pcNote: "RDNA2 via Cemu often exceeds real Switch performance. Vulkan backend recommended. (Note: A Switch 2 Edition exists, but Cemu is the optimal PC emulation path.)",
      style: "Open-world action-adventure",
      campaign: "40–60 hrs main · 100+ hrs full",
      timelineBranch: "Post-timeline (after all three branches)",
      protagonist: "Link",
      shortDesc: "Link wakes with no memory in a ruined Hyrule. Calamity Ganon destroyed everything 100 years ago. Zelda is trapped, sacrificing herself to contain him.",
      storyRole: "Begins the modern arc. Establishes the Calamity, the Champions, and Zelda's sacrifice. The entire ancient history of Hyrule is hinted at but not explained — TotK fills that in.",
      connectsTo: "Tears of the Kingdom — direct sequel, same world, Link and Zelda continue.",
      expandDetails: "Completely open from the first moments. Climb any surface. Physics and chemistry engine — fire spreads, metal conducts lightning, logs float. 120 Shrine puzzles replace traditional dungeons. Four Divine Beasts as major encounters. Weapon durability is divisive but manageable. The recovered memory fragments of Link and Zelda's past give the game unexpected emotional weight."
    },
    {
      id: "totk",
      title: "Tears of the Kingdom",
      year: 2023,
      tier: "Tier 1 — Best Looking, Runs Great",
      tierClass: "tier1",
      platform: "Switch",
      emulator: "Ryujinx (Switch)",
      yourPC: "⚠️ Worth trying — low/medium settings",
      pcNote: "Demanding but playable. Use Vulkan, set resolution to 1x, disable MSAA. (Note: A Switch 2 Edition exists, but Switch 1 via Ryujinx is the viable PC path.)",
      style: "Open-world action-adventure (expanded)",
      campaign: "50–80 hrs main · 150+ hrs full",
      timelineBranch: "Post-timeline — direct BotW sequel",
      protagonist: "Link",
      shortDesc: "Ganondorf awakens beneath Hyrule Castle. Zelda vanishes into the distant past. Link falls into the sky and must rebuild Hyrule — and find her.",
      storyRole: "Reveals the true ancient history: the Zonai civilisation, King Rauru, the first Imprisoning War, and Ganondorf's true origin. Zelda's sacrifice and what it means is the emotional core.",
      connectsTo: "Age of Imprisonment (2025) — set during the Imprisoning War Zelda witnesses in TotK.",
      expandDetails: "New abilities: Ultrahand (build machines from Zonai parts), Fuse (combine weapons), Ascend (pass through ceilings), Recall (reverse time on objects). Sky islands above Hyrule. The Depths — a vast underground mirror of the surface. Metacritic 96. The most ambitious Zelda ever made."
    },
    {
      id: "hw-aoi",
      title: "Hyrule Warriors: Age of Imprisonment",
      year: 2025,
      tier: "Tier 1 — Best Looking, Runs Great",
      tierClass: "tier1",
      platform: "Switch 2",
      emulator: "Ryujinx (Pending / Switch 2)",
      yourPC: "⚠️ Needs Testing",
      pcNote: "Switch 2 emulation on RDNA2 architecture may be highly demanding or experimental at this stage. Expect caching stutters.",
      style: "Hack-and-slash / Action",
      campaign: "30–40 hrs",
      timelineBranch: "Post-timeline — The Imprisoning War",
      protagonist: "Zelda · King Rauru",
      shortDesc: "Set during the Imprisoning War in the ancient past of the Wild Era. Zelda and King Rauru fight to seal the Demon King Ganondorf in this canonical prequel to Tears of the Kingdom.",
      storyRole: "Provides a playable narrative backdrop to the events only seen in fragmented memories during Tears of the Kingdom. The only canonical Hyrule Warriors game.",
      connectsTo: "Breath of the Wild — set tens of thousands of years before the Calamity.",
      expandDetails: "Following the tradition of the Hyrule Warriors series, it features large-scale battles where players fight hordes of enemies. Features playable characters like Princess Zelda, King Rauru, and Queen Sonia, introducing new mechanics like Sync Strikes and Zonai devices in combat."
    },
    {
      id: "wwhd",
      title: "The Wind Waker HD",
      year: 2013,
      tier: "Tier 1 — Best Looking, Runs Great",
      tierClass: "tier1",
      platform: "Wii U",
      emulator: "Cemu (Wii U)",
      yourPC: "✅ Runs great",
      pcNote: "Cemu runs Wind Waker HD perfectly. Enable 60fps patch for buttery smooth gameplay.",
      style: "3D cel-shaded action-adventure / sailing",
      campaign: "25–35 hrs",
      timelineBranch: "Adult Era — follows Ocarina of Time",
      protagonist: "Link (new incarnation, Toon Link)",
      shortDesc: "Hyrule was drowned by the gods to stop Ganon. A boy on Outset Island discovers he is the next chosen hero when his sister is kidnapped by a giant bird.",
      storyRole: "The gods flooded Hyrule when no hero appeared in time. This is the result — a new world of scattered islands above the sunken kingdom. The King of Hyrule's final farewell is one of the most emotional moments in the franchise.",
      connectsTo: "Phantom Hourglass — direct sequel, same Toon Link, same ocean world.",
      expandDetails: "Cel-shaded art style was controversial in 2002, now universally beloved as timeless. Ocean overworld navigated by sailing and controlling wind direction with a magical baton. Swift Sail added in HD version removes the slow sailing complaint. Found-family dynamic with the pirate crew. The King of Hyrule's final wish — and what he wishes for — reframes everything."
    },
    {
      id: "tphd",
      title: "Twilight Princess HD",
      year: 2016,
      tier: "Tier 1 — Best Looking, Runs Great",
      tierClass: "tier1",
      platform: "Wii U",
      emulator: "Cemu (Wii U)",
      yourPC: "✅ Runs great",
      pcNote: "Runs perfectly on Cemu. 1080p, Hero Mode available from start. Best version.",
      style: "3D dark action-adventure",
      campaign: "35–45 hrs",
      timelineBranch: "Child Era — follows Majora's Mask",
      protagonist: "Link · Midna",
      shortDesc: "Hyrule is consumed by Twilight. Link is transformed into a wolf. Midna — a mysterious imp — becomes his guide and the game's true emotional protagonist.",
      storyRole: "Ganondorf was banished to the Twilight Realm by the sages after Ocarina of Time's Child Timeline. He infected it and sent Zant to conquer Hyrule. Midna's arc — from contempt to sacrifice — is the finest character writing in the franchise.",
      connectsTo: "Four Swords Adventures — set after Twilight Princess in the Child Timeline.",
      expandDetails: "The most tonally dark console Zelda. Wolf transformation in the Twilight Realm loses sword and items but gains heightened senses. Midna sits on wolf-Link's back and is present in every moment of the game — her relationship with Link is built gradually and pays off fully. Hero Mode unlocks at completion for a harder replay with no recovery hearts."
    },
    {
      id: "sshd",
      title: "Skyward Sword HD",
      year: 2021,
      tier: "Tier 1 — Best Looking, Runs Great",
      tierClass: "tier1",
      platform: "Switch",
      emulator: "Ryujinx (Switch)",
      yourPC: "⚠️ Worth trying — low/medium settings",
      pcNote: "Use button controls mode — far better than motion in emulation. Runs adequately on low settings.",
      style: "3D action-adventure — origin story",
      campaign: "35–45 hrs",
      timelineBranch: "Root Timeline — the earliest entry in all of canon",
      protagonist: "Link · Zelda",
      shortDesc: "Before Hyrule existed, the goddess Hylia protected the Triforce from the demon king Demise. She reincarnated as a mortal — Zelda. And she needs Link to forge the Master Sword.",
      storyRole: "The origin of everything: the Master Sword, the Triforce, Ganon's curse, Hyrule itself. Demise's dying curse — his hatred reincarnating forever as Ganon — is the engine driving every other game in the franchise. This is the why behind all of it.",
      connectsTo: "The Minish Cap — set after Skyward Sword, explains Vaati and the Four Sword.",
      expandDetails: "Link and Zelda grew up together in Skyloft — a floating island above the clouds. Their relationship is the most explicitly personal in the series. Fi, the spirit of the Goddess Sword, guides Link — divisive for her constant interruptions, much improved in HD. Optional button controls in the Switch HD version make this far more playable than the Wii original."
    },
    {
      id: "oot3d",
      title: "Ocarina of Time 3D",
      year: 2011,
      tier: "Tier 2 — Remasters, Still Look Great",
      tierClass: "tier2",
      platform: "Nintendo 3DS",
      emulator: "Citra",
      yourPC: "✅ Runs great",
      pcNote: "Citra runs OoT3D perfectly at full speed. Widescreen patch recommended.",
      style: "3D action-adventure — the split point",
      campaign: "25–30 hrs",
      timelineBranch: "Root Timeline — the timeline split point",
      protagonist: "Link (child and adult)",
      shortDesc: "Young Link pulls the Master Sword and is sealed for seven years. He wakes as an adult to find Ganondorf has conquered Hyrule. The timeline splits from this single moment.",
      storyRole: "The most important game in the franchise. Ganondorf's first true rise. The Sacred Realm corrupted into the Dark Realm. Young Link sent back to childhood by Zelda after victory — creating the Child Era and Adult Era simultaneously. The Downfall Timeline branches from the possibility that the Hero fails here.",
      connectsTo: "Three branches simultaneously: Majora's Mask (Child Era) · Wind Waker (Adult Era) · A Link to the Past (Downfall — Hero Defeated).",
      expandDetails: "Metacritic 99/100 — Guinness record for highest-rated game in history. Introduced Z-targeting, context-sensitive controls, Epona, and 3D dungeon design that defined an entire generation of action games. The 3DS remaster features fully remade graphics, widescreen, and an improved UI. The Master Quest (a remixed, harder dungeon layout) is also included and unlocks after beating the game. The Water Temple — infamous in the N64 original — has been restructured and is far less frustrating here."
    },
    {
      id: "mm3d",
      title: "Majora's Mask 3D",
      year: 2015,
      tier: "Tier 2 — Remasters, Still Look Great",
      tierClass: "tier2",
      platform: "Nintendo 3DS",
      emulator: "Citra",
      yourPC: "✅ Runs great",
      pcNote: "Citra handles MM3D perfectly. Improved Bomber's Notebook UI makes tracking quests much easier.",
      style: "3D action-adventure — time loop",
      campaign: "25–35 hrs",
      timelineBranch: "Child Era — direct OoT sequel",
      protagonist: "Link",
      shortDesc: "Link enters Termina — a parallel world. A moon is falling. He has 72 hours before it destroys everything. He must relive those hours, again and again, until he can save every soul.",
      storyRole: "Child Link after Ocarina of Time, searching for a lost friend. Termina is a mirror of Hyrule — same faces, different lives, different tragedies. Every character has a complete arc across the three days if you follow them. The darkest, most emotionally complex Zelda ever made.",
      connectsTo: "Twilight Princess — set after Majora's Mask in the Child Era.",
      expandDetails: "Time resets every 72 in-game hours via the Song of Time. Link accumulates knowledge, items, and relationships across loops — only certain things carry over. Mask transformation system: Deku, Goron, Zora — each with unique abilities. Fewer traditional dungeons than OoT but the side quests and character writing are unmatched in the franchise."
    },
    {
      id: "la-switch",
      title: "Link's Awakening (Switch Remake)",
      year: 2019,
      tier: "Tier 2 — Remasters, Still Look Great",
      tierClass: "tier2",
      platform: "Switch",
      emulator: "Ryujinx",
      yourPC: "⚠️ Worth trying",
      pcNote: "Runs on low-medium settings via Ryujinx. Some frame drops in outdoor areas — manageable.",
      style: "Top-down action-adventure — dream island",
      campaign: "8–12 hrs",
      timelineBranch: "Downfall Timeline — follows A Link to the Past",
      protagonist: "Link",
      shortDesc: "Link is shipwrecked on Koholint Island. The only way to leave is to wake the Wind Fish — a sleeping god whose dream the island exists inside.",
      storyRole: "A standalone story between A Link to the Past and the Oracle games. The island and every person on it exists only inside the Wind Fish's dream. Link must choose to wake it — which ends everything. One of the franchise's most quietly devastating endings.",
      connectsTo: "Oracle of Seasons / Oracle of Ages — Link continues his journey after leaving Koholint.",
      expandDetails: "Toy-box diorama art style — miniature figurine aesthetic that makes the dreamlike tone physical and visible. Full remake of the 1993 Game Boy original. Dungeon creator mode added for replayability. The melancholy of the ending hits harder in this version because you have seen these characters, their homes, their lives — and you know what waking up means for them."
    },
    {
      id: "albw",
      title: "A Link Between Worlds",
      year: 2013,
      tier: "Tier 3 — 3DS Originals, Clean & Playable",
      tierClass: "tier3",
      platform: "Nintendo 3DS",
      emulator: "Citra",
      yourPC: "✅ Runs great",
      pcNote: "Perfect speed on Citra. Enable stereoscopic 3D emulation for the full experience.",
      style: "Top-down action-adventure — open dungeon order",
      campaign: "12–16 hrs",
      timelineBranch: "Downfall Timeline — six generations after A Link to the Past",
      protagonist: "Link",
      shortDesc: "A sorcerer named Yuga is turning Hyrule's sages into paintings. Link gains the ability to merge into walls as a 2D painting to pursue him into the parallel kingdom of Lorule.",
      storyRole: "Six generations after A Link to the Past. The Triforce is reunited. Ganon is resurrected — then defeated again. Lorule is a mirror of Hyrule that destroyed its own Triforce and is dying. Princess Hilda's desperation drives the conflict.",
      connectsTo: "Tri Force Heroes — set a few years later in the same era.",
      expandDetails: "Open dungeon progression — rent or buy items from Ravio's shop rather than finding them in dungeons, then tackle the last seven dungeons in any order. Revolutionary for the series. The wall-merge mechanic enables entirely new puzzle design. Tight, well-paced, and beautifully designed. One of the 3DS's finest games."
    },
    {
      id: "triforceh",
      title: "Tri Force Heroes",
      year: 2015,
      tier: "Tier 3 — 3DS Originals, Clean & Playable",
      tierClass: "tier3",
      platform: "Nintendo 3DS",
      emulator: "Citra",
      yourPC: "✅ Runs great",
      pcNote: "Runs perfectly on Citra.",
      style: "Co-op multiplayer puzzle-adventure",
      campaign: "10–15 hrs",
      timelineBranch: "Downfall Timeline — follows A Link Between Worlds",
      protagonist: "Link (three Links simultaneously)",
      shortDesc: "Link is summoned to the fashion-obsessed kingdom of Hytopia, cursed by the Drablands witch. Three heroes must stack on each other's shoulders to reach high areas and solve puzzles.",
      storyRole: "Light narrative — the weakest story in the Downfall Timeline. Primarily a co-op puzzle experience. Completes the timeline slot before Echoes of Wisdom. Play for completion.",
      connectsTo: "Echoes of Wisdom — set after Tri Force Heroes, before the original 1986 Zelda.",
      expandDetails: "Three-player co-op with stacking mechanic — players climb on top of each other to reach heights. Solo with AI partners is significantly weaker. Costume system provides gameplay bonuses. Enjoyable as a multiplayer experience; thin as a solo story."
    },
    {
      id: "eow",
      title: "Echoes of Wisdom",
      year: 2024,
      tier: "Tier 3 — 3DS Originals, Clean & Playable",
      tierClass: "tier3",
      platform: "Switch",
      emulator: "Ryujinx",
      yourPC: "⚠️ Worth trying",
      pcNote: "Runs on low settings via Ryujinx. Top-down perspective is less demanding than 3D open-world titles.",
      style: "Top-down action-adventure",
      campaign: "15–20 hrs",
      timelineBranch: "Downfall Timeline — after Tri Force Heroes, before original Zelda",
      protagonist: "Princess Zelda — first time as sole main protagonist",
      shortDesc: "Rifts are opening across Hyrule, swallowing everything into the Still World. Link is absorbed. For the first time, Zelda must save herself — and him.",
      storyRole: "Historic entry. Zelda uses the Tri Rod to copy enemies and objects as Echoes — recreating them to solve puzzles and fight. Link is largely absent. Places Zelda as an active agent of her own story for the first time in the mainline series.",
      connectsTo: "The Legend of Zelda (1986) — this is the entry immediately before the original game in the Downfall Timeline.",
      expandDetails: "Combat is indirect — Zelda cannot directly attack most enemies. She summons Echoes of things she has encountered: a bed to float over spikes, a monster to fight for her, a rock to block a path. Swordfighter form available briefly after charging. Metacritic 85. Significant for what it represents as much as what it plays like."
    },
    {
      id: "fsa",
      title: "Four Swords Adventures",
      year: 2004,
      tier: "Tier 4 — GameCube / Wii Era via Dolphin",
      tierClass: "tier4",
      platform: "GameCube",
      emulator: "Dolphin",
      yourPC: "✅ Runs great",
      pcNote: "Dolphin runs GC titles excellently on your RDNA2. Use Vulkan backend.",
      style: "Top-down level-based adventure",
      campaign: "15–20 hrs",
      timelineBranch: "Child Era — set after Twilight Princess and Four Swords",
      protagonist: "Link (four Links)",
      shortDesc: "Shadow forces steal the Dark Mirror and release a Gerudo man — a rare occurrence every hundred years — who becomes the demon king Ganondorf in this era.",
      storyRole: "Completes the Child Era. This Ganondorf is a different reincarnation — not the same person as in Ocarina of Time. He stole the Trident of Power and became the Demon King. The Four Sword seals him.",
      connectsTo: "This is the final entry in the Child Era branch.",
      expandDetails: "Linear level structure — no connecting overworld. 24 levels across eight worlds. Two modes: Hyrulean Adventure (story) and Shadow Battle (versus). The Japanese and Korean versions include Navi Trackers with voice acting — unique to those regions. Completionists only for Western players."
    },
    {
      id: "ph",
      title: "Phantom Hourglass",
      year: 2007,
      tier: "Tier 4 — GameCube / Wii Era via Dolphin",
      tierClass: "tier4",
      platform: "Nintendo DS",
      emulator: "Citra (DS mode)",
      yourPC: "✅ Runs great",
      pcNote: "Citra handles DS mode well. Touch input mapped to mouse.",
      style: "Top-down 3D — touch screen controls",
      campaign: "15–20 hrs",
      timelineBranch: "Adult Era — direct Wind Waker sequel",
      protagonist: "Link (Toon Link)",
      shortDesc: "Tetra is captured by the Ghost Ship. Link sails a new ocean with Linebeck, a cowardly captain, guided by the spirit of the Ocean King — Ciela.",
      storyRole: "Continues directly from Wind Waker's ending. The Ocean King is being drained of his life force by Bellum. The Temple of the Ocean King — a central dungeon revisited repeatedly — contains the Phantom Hourglass that limits time inside.",
      connectsTo: "Spirit Tracks — set 100 years later in a new land settled by the descendants of Wind Waker's characters.",
      expandDetails: "All controls via touch screen — draw paths for boomerang, tap to move and attack. The repeating Temple of the Ocean King is divisive — you gain more time with each visit but must replay earlier floors. Linebeck is a genuinely funny and eventually touching companion character."
    },
    {
      id: "st",
      title: "Spirit Tracks",
      year: 2009,
      tier: "Tier 4 — GameCube / Wii Era via Dolphin",
      tierClass: "tier4",
      platform: "Nintendo DS",
      emulator: "Citra (DS mode)",
      yourPC: "✅ Runs great",
      pcNote: "Runs well on Citra. Microphone required for one puzzle — use keyboard workaround in emulation.",
      style: "Top-down 3D — touch screen / train traversal",
      campaign: "15–20 hrs",
      timelineBranch: "Adult Era — ~100 years after Phantom Hourglass",
      protagonist: "Link · Princess Zelda (spirit companion)",
      shortDesc: "The Spirit Tracks — railroads that chain an ancient evil — are vanishing. Zelda's body is stolen by Chancellor Cole for the resurrection of the Demon King. She becomes a spirit companion.",
      storyRole: "Zelda is more active here than in almost any other game. As a spirit, she can possess Phantom Knights that the player controls in dungeons — working in tandem with Link. Her personality is fully present throughout. Important precursor to Echoes of Wisdom's approach to Zelda.",
      connectsTo: "This is the final entry in the Adult Era branch.",
      expandDetails: "Train replaces boat as overworld traversal — drawing routes on the map. Zelda-as-Phantom is a genuine co-op puzzle mechanic. Flute instrument played via touch and microphone. The Demon King Malladus and Chancellor Cole are underrated antagonists. Stronger character writing than Phantom Hourglass."
    },
    {
      id: "ss-wii",
      title: "Skyward Sword (Wii original)",
      year: 2011,
      tier: "Tier 4 — GameCube / Wii Era via Dolphin",
      tierClass: "tier4",
      platform: "Wii",
      emulator: "Dolphin",
      yourPC: "✅ Runs great (motion controls tricky)",
      pcNote: "Dolphin can emulate Wii MotionPlus via mouse+keyboard — workable but imperfect. HD version strongly preferred.",
      style: "3D — motion swordplay (Wii original)",
      campaign: "35–45 hrs",
      timelineBranch: "Root Timeline — same as HD version",
      protagonist: "Link",
      shortDesc: "Same game as Skyward Sword HD — Wii original with motion controls.",
      storyRole: "Same as Skyward Sword HD. Play the HD version instead if possible.",
      connectsTo: "Same as Skyward Sword HD.",
      expandDetails: "Only include this if you specifically want the motion control experience. Dolphin's mouse emulation for Wii MotionPlus is functional but less precise than real hardware. The HD version with button controls is a significantly better experience. Skip this entry if you played the HD version."
    },
    {
      id: "mc",
      title: "The Minish Cap",
      year: 2004,
      tier: "Tier 5 — GBA / DS Originals",
      tierClass: "tier5",
      platform: "Game Boy Advance",
      emulator: "mGBA",
      yourPC: "✅ Runs great",
      pcNote: "mGBA runs all GBA titles at perfect speed. Minimal system demand.",
      style: "Top-down action-adventure",
      campaign: "12–15 hrs",
      timelineBranch: "Root Timeline — prequel to Four Swords",
      protagonist: "Link",
      shortDesc: "Vaati, a sorcerer seeking the Light Force, petrifies Zelda. Link gains the Mage's Cap — Ezlo — which allows him to shrink to Minish size. The Minish are tiny beings who secretly bless Hyrule.",
      storyRole: "Explains Vaati's origin and how the Four Sword was created to seal him. Precedes the Four Swords game directly. The Minish — called Picori — are confirmed canon and referenced in other entries.",
      connectsTo: "Four Swords — Vaati is sealed in the Four Sword directly after this game's events.",
      expandDetails: "Developed by Capcom under Nintendo supervision. Shrinking mechanic opens entirely new areas in familiar spaces — furniture becomes environments, blades of grass become a forest. Kinstones side quest — fusing half-medallions with characters to unlock secrets across the world. One of the GBA's finest games and an underrated Zelda entry."
    },
    {
      id: "oos",
      title: "Oracle of Seasons",
      year: 2001,
      tier: "Tier 5 — GBA / DS Originals",
      tierClass: "tier5",
      platform: "Game Boy Color",
      emulator: "mGBA",
      yourPC: "✅ Runs great",
      pcNote: "mGBA runs GBC titles at perfect speed.",
      style: "Top-down action-adventure — seasonal manipulation",
      campaign: "10–12 hrs",
      timelineBranch: "Downfall Timeline — follows Link's Awakening",
      protagonist: "Link",
      shortDesc: "Din, the Oracle of Seasons, is captured by General Onox. The seasons of Holodrum fall into chaos. Link wields the Rod of Seasons to shift between them and restore order.",
      storyRole: "One half of an interconnected pair. More action-focused. Completing this game generates a password to continue into Oracle of Ages as a direct sequel — unlocking a true final boss and the mastermind behind both games: Twinrova, acting to resurrect Ganon.",
      connectsTo: "Oracle of Ages — play immediately after Seasons using the password for the true ending.",
      expandDetails: "Developed by Capcom/Flagship. Seasonal manipulation is the core mechanic — different seasons transform the overworld: summer dries up water, winter freezes it, spring blooms new paths. Eight dungeons. The linked game experience with Oracle of Ages is the intended way to play."
    },
    {
      id: "ooa",
      title: "Oracle of Ages",
      year: 2001,
      tier: "Tier 5 — GBA / DS Originals",
      tierClass: "tier5",
      platform: "Game Boy Color",
      emulator: "mGBA",
      yourPC: "✅ Runs great",
      pcNote: "mGBA runs GBC titles at perfect speed.",
      style: "Top-down action-adventure — time travel",
      campaign: "10–12 hrs + true ending",
      timelineBranch: "Downfall Timeline — follows Oracle of Seasons",
      protagonist: "Link",
      shortDesc: "Nayru, the Oracle of Ages, is possessed by Veran, a sorceress of shadows. Link travels between present and past Labrynna to undo the damage.",
      storyRole: "The second half of the Oracle pair. More puzzle-focused. When played after Seasons with the password, an extended epilogue reveals Twinrova — Ganon's surrogate mothers — were behind both games, lighting three flames of evil to resurrect Ganon. Their plan partially succeeds but produces only a mindless beast.",
      connectsTo: "A Link to the Past — Ganon's full resurrection is prevented here; his shadow continues in ALttP.",
      expandDetails: "Time travel between two eras of Labrynna changes the landscape — the past is wilder, the present more developed. Puzzles require understanding how your past actions reshape the future. The linked game's true ending and final boss are only accessible when playing as a sequel to Oracle of Seasons."
    },
    {
      id: "fs",
      title: "Four Swords",
      year: 2002,
      tier: "Tier 5 — GBA / DS Originals",
      tierClass: "tier5",
      platform: "Game Boy Advance",
      emulator: "mGBA (Anniversary Edition for solo)",
      yourPC: "✅ Runs great",
      pcNote: "Four Swords Anniversary Edition (DSiWare) added solo mode — use that version on Citra.",
      style: "Multiplayer co-op action-adventure",
      campaign: "3–5 hrs",
      timelineBranch: "Root Timeline — predates Ocarina of Time",
      protagonist: "Link (up to four)",
      shortDesc: "Vaati has escaped the Four Sword and kidnapped maidens including Princess Zelda. Link pulls the Four Sword, splitting himself into four copies to pursue him.",
      storyRole: "Explains how Vaati escaped after the Minish Cap events and was resealed. Sets up the Four Sword as a recurring artifact. Primarily a multiplayer experience — story is minimal.",
      connectsTo: "Ocarina of Time — Four Swords predates OoT in the timeline, establishing the Four Sword's existence.",
      expandDetails: "First multiplayer Zelda. Originally bundled with A Link to the Past on GBA. Introduced Toon Link visual style. Anniversary Edition added a solo mode and a special Palace of the Four Sword. Short and minor — play for completion. The multiplayer experience is its real value."
    },
    {
      id: "lttp",
      title: "A Link to the Past",
      year: 1991,
      tier: "Tier 6 — SNES / NES Originals",
      tierClass: "tier6",
      platform: "Super NES",
      emulator: "Snes9x / RetroArch",
      yourPC: "✅ Runs great",
      pcNote: "SNES emulation is trivial. Runs at perfect speed on any hardware.",
      style: "Top-down action-adventure — the definitive 2D Zelda",
      campaign: "10–15 hrs",
      timelineBranch: "Downfall Timeline — after the Hero falls in Ocarina of Time",
      protagonist: "Link",
      shortDesc: "Agahnim, a wizard serving as Ganon's alter ego, is breaking the seal on the Sacred Realm. Link discovers the Light World and Dark World — a corrupted mirror of Hyrule — and must save seven maidens to confront Ganon.",
      storyRole: "Established the Triforce mythology, the Master Sword, the Sacred Realm, and the Light/Dark World duality that echoes through the entire series. Ganon's origin as the Gerudo thief Ganondorf who touched the Triforce with an unbalanced heart is explained here. One of the most influential games ever made.",
      connectsTo: "Link's Awakening — immediately after ALttP, Link sets sail and is shipwrecked on Koholint Island.",
      expandDetails: "Cited as a direct influence on Dark Souls, Grand Theft Auto III, Assassin's Creed IV, Soul Reaver, and countless others. Thirteen dungeons across two worlds. Tight design, iconic music, perfect pacing. Dark World versions of overworld areas reflect the corruption of whatever you carry in your heart. The GBA port added a bonus dungeon. Still completely holds up."
    },
    {
      id: "la-gb",
      title: "Link's Awakening (Original GB/GBC)",
      year: 1993,
      tier: "Tier 6 — SNES / NES Originals",
      tierClass: "tier6",
      platform: "Game Boy / Game Boy Color",
      emulator: "mGBA",
      yourPC: "✅ Runs great",
      pcNote: "Skip if you played the Switch remake — identical story. GBC version (Link's Awakening DX) adds a colour dungeon.",
      style: "Top-down action-adventure",
      campaign: "8–12 hrs",
      timelineBranch: "Downfall Timeline — follows A Link to the Past",
      protagonist: "Link",
      shortDesc: "Same story as the Switch remake. Shipwrecked on Koholint Island. The Wind Fish sleeps. Link must wake it.",
      storyRole: "Same as Switch remake. Play this only if you want the original Game Boy experience or the DX colour dungeon.",
      connectsTo: "Oracle of Seasons — Link leaves Koholint and continues his journey.",
      expandDetails: "The GBC version (DX) adds the Colour Dungeon — a dungeon exclusive to the colour version that rewards a tunic upgrade. Otherwise identical to the Switch remake in story. The original pixel art has its own charm that the remake's diorama style replaces. Both are valid experiences."
    },
    {
      id: "loz",
      title: "The Legend of Zelda (1986)",
      year: 1986,
      tier: "Tier 6 — SNES / NES Originals",
      tierClass: "tier6",
      platform: "NES / Famicom Disk System",
      emulator: "RetroArch / Nestopia",
      yourPC: "✅ Runs great",
      pcNote: "NES emulation is effortless. Any RetroArch core handles this.",
      style: "Top-down action-adventure — the origin",
      campaign: "6–10 hrs + Second Quest",
      timelineBranch: "Downfall Timeline — near the end of the branch",
      protagonist: "Link",
      shortDesc: "Ganon has stolen the Triforce of Power. Zelda shattered the Triforce of Wisdom into eight pieces to keep it from him. Link must recover all eight from nine dungeons and defeat Ganon.",
      storyRole: "The original. Where it all began. After all the prequels and sequels and parallel timelines — this is the moment the franchise was born. In the Downfall Timeline, this is one of the final confrontations with Ganon before Zelda II.",
      connectsTo: "Zelda II: The Adventure of Link — a direct sequel set years later.",
      expandDetails: "First console game with a save function. Fully open from the start — no hand-holding, no map markers, no direction. The Second Quest — accessible by naming your file ZELDA — remixes all dungeons with different layouts and harder enemies. The game that created the action-adventure genre."
    },
    {
      id: "z2",
      title: "Zelda II: The Adventure of Link",
      year: 1987,
      tier: "Tier 6 — SNES / NES Originals",
      tierClass: "tier6",
      platform: "NES / Famicom Disk System",
      emulator: "RetroArch / Nestopia",
      yourPC: "✅ Runs great",
      pcNote: "NES emulation is effortless.",
      style: "Side-scrolling action RPG — unique to series",
      campaign: "8–12 hrs",
      timelineBranch: "Downfall Timeline — final entry in the branch",
      protagonist: "Link",
      shortDesc: "A mark appears on Link's hand. He discovers a sleeping Princess Zelda — different from the one he saved — cursed by a wizard. Six crystals must be placed in palace statues to unlock the Great Palace and the Triforce of Courage.",
      storyRole: "The Triforce of Courage is introduced here — obtained by Link at the end of his quest. With all three Triforce pieces united, Hyrule enters an era of peace. This is the resolution of the Downfall Timeline.",
      connectsTo: "This is the final entry in the Downfall Timeline — the branch concludes here.",
      expandDetails: "The black sheep of the franchise. Side-scrolling combat with a jump button. Experience points and level-up system — the only RPG mechanics in any mainline Zelda. Notoriously difficult. Towns populated by named NPCs — some names became recurring across the series. The Game Over screen's GAME OVER in red is iconic. Worth playing for completion and history."
    }
  ],

  // ─────────────────────────────────────────────
  // SECTION 2: RELEASE ORDER
  // ─────────────────────────────────────────────
  byRelease: [
    { id: "loz", year: 1986 },
    { id: "z2", year: 1987 },
    { id: "lttp", year: 1991 },
    { id: "la-gb", year: 1993 },
    { id: "oot3d-orig", year: 1998, isOriginal: true, refId: "oot3d", originalTitle: "Ocarina of Time (N64 original)", originalEmulator: "Citra (3DS remaster preferred)", originalPlatform: "Nintendo 64" },
    { id: "mm3d-orig", year: 2000, isOriginal: true, refId: "mm3d", originalTitle: "Majora's Mask (N64 original)", originalEmulator: "Citra (3DS remaster preferred)", originalPlatform: "Nintendo 64" },
    { id: "oos", year: 2001 },
    { id: "ooa", year: 2001 },
    { id: "fs", year: 2002 },
    { id: "ww-orig", year: 2002, isOriginal: true, refId: "wwhd", originalTitle: "The Wind Waker (GameCube original)", originalEmulator: "Dolphin / Cemu HD preferred", originalPlatform: "GameCube" },
    { id: "fsa", year: 2004 },
    { id: "mc", year: 2004 },
    { id: "tp-orig", year: 2006, isOriginal: true, refId: "tphd", originalTitle: "Twilight Princess (Wii/GC original)", originalEmulator: "Dolphin / Cemu HD preferred", originalPlatform: "Wii / GameCube" },
    { id: "ph", year: 2007 },
    { id: "st", year: 2009 },
    { id: "oot3d", year: 2011 },
    { id: "ss-wii", year: 2011 },
    { id: "wwhd", year: 2013 },
    { id: "albw", year: 2013 },
    { id: "mm3d", year: 2015 },
    { id: "triforceh", year: 2015 },
    { id: "tphd", year: 2016 },
    { id: "botw", year: 2017 },
    { id: "la-switch", year: 2019 },
    { id: "sshd", year: 2021 },
    { id: "totk", year: 2023 },
    { id: "eow", year: 2024 },
    { id: "hw-aoi", year: 2025 }
  ],

  // ─────────────────────────────────────────────
  // SECTION 3: IN-UNIVERSE CHRONOLOGICAL ORDER
  // ─────────────────────────────────────────────
  byChronological: [
    {
      branch: "Root Timeline (Pre-Split)",
      color: "#c9a84c",
      games: [
        { id: "sshd", chronNote: "The very beginning of all Hyrulean history. Demise curses all future iterations of Link and Zelda." },
        { id: "mc", chronNote: "Vaati's origin. The Four Sword is forged to seal him." },
        { id: "fs", chronNote: "Vaati escapes and is resealed by the newly-forged Four Sword." },
        { id: "oot3d", chronNote: "The timeline splits here. Young Link vs Adult Link creates three simultaneous futures." }
      ]
    },
    {
      branch: "Child Era (Hero Returns to Childhood)",
      color: "#6fa3d0",
      games: [
        { id: "mm3d", chronNote: "Link searches for a lost friend. Termina. The falling moon. Three days forever." },
        { id: "tphd", chronNote: "Ganondorf — banished after OoT — conquers from the Twilight Realm. Midna's arc." },
        { id: "fsa", chronNote: "A new Ganondorf reincarnation is sealed by the Four Sword. Child Era concludes." }
      ]
    },
    {
      branch: "Adult Era (Hero Remains in Future)",
      color: "#7db87d",
      games: [
        { id: "wwhd", chronNote: "Hyrule drowned. A new ocean world. The King of Hyrule's farewell." },
        { id: "ph", chronNote: "Toon Link sails a new ocean. The Ocean King's life force is being stolen." },
        { id: "st", chronNote: "100 years later. Zelda's body stolen. She becomes Link's spirit companion." }
      ]
    },
    {
      branch: "Downfall Timeline (Hero Defeated in OoT)",
      color: "#b87d7d",
      games: [
        { id: "lttp", chronNote: "Agahnim/Ganon breaks the Sacred Realm seal. Dark World. Seven maidens. The definitive 2D Zelda." },
        { id: "la-gb", chronNote: "Link shipwrecked. Koholint Island. The Wind Fish's dream. A devastating choice." },
        { id: "oos", chronNote: "Din captured. Seasons in chaos. Play first of the Oracle pair." },
        { id: "ooa", chronNote: "Nayru possessed. Time travel in Labrynna. True ending requires Oracle of Seasons password." },
        { id: "albw", chronNote: "Six generations later. Lorule's dying Triforce. Open dungeon order. Wall-merging." },
        { id: "triforceh", chronNote: "Hytopia cursed. Three Links. Light narrative — play for completion." },
        { id: "eow", chronNote: "Zelda as protagonist for the first time. Rifts swallow Hyrule. Link is taken." },
        { id: "loz", chronNote: "The original game. Nine dungeons. Ganon defeated. Where it all began." },
        { id: "z2", chronNote: "The Triforce of Courage obtained. Hyrule enters peace. The timeline resolves." }
      ]
    },
    {
      branch: "Post-Timeline (After All Three Branches)",
      color: "#9b7db8",
      games: [
        { id: "hw-aoi", chronNote: "The Imprisoning War. Zelda and King Rauru seal the Demon King in the ancient past." },
        { id: "botw", chronNote: "The modern era. Tens of thousands of years later. Link and Zelda vs Calamity Ganon." },
        { id: "totk", chronNote: "Ganondorf's true origin revealed. The final resolution." }
      ]
    }
  ]
};

// Build lookup map
GAMES.lookup = {};
GAMES.byVisual.forEach(g => GAMES.lookup[g.id] = g);

// Spin-offs (Worth Playing)
GAMES.spinoffs = [
  {
    id: "aoc",
    title: "Hyrule Warriors: Age of Calamity",
    year: 2020,
    tierClass: "tier2",
    platform: "Switch",
    emulator: "Ryujinx",
    yourPC: "⚠️ Demanding",
    pcNote: "Hack-and-slash games are CPU intensive. Expect frame dips during heavy combat and particle effects. Vulkan recommended.",
    style: "Hack-and-slash / Action",
    campaign: "20–30 hrs",
    timelineBranch: "Alternate Wild Era timeline",
    protagonist: "Link · Zelda · Champions",
    shortDesc: "An alternate-timeline prequel to Breath of the Wild. Experience the Great Calamity firsthand.",
    storyRole: "Non-canonical to the main BotW timeline, but features excellent character work for the Champions that expanded their personalities significantly.",
    expandDetails: "A 'Warriors' style game. A small guardian named Terrako travels back in time, splitting the timeline and allowing a different outcome to the tragic events of BotW's past.",
    connectsTo: "Parallel to Breath of the Wild."
  },
  {
    id: "cadence",
    title: "Cadence of Hyrule",
    year: 2019,
    tierClass: "tier2",
    platform: "Switch",
    emulator: "Ryujinx",
    yourPC: "✅ Runs great",
    pcNote: "2D rhythm games are light on CPU/GPU. Runs flawlessly via Vulkan.",
    style: "Rhythm Roguelite / Action",
    campaign: "5–10 hrs",
    timelineBranch: "Spin-off",
    protagonist: "Cadence · Link · Zelda",
    shortDesc: "An officially licensed rhythm-based roguelite crossover with Crypt of the NecroDancer.",
    storyRole: "Standalone experience with no bearing on mainline lore. Purely focused on gameplay, exploration, and incredible music.",
    expandDetails: "Explore a randomly generated overworld and dungeons, moving and fighting to the beat of remixed Zelda music. A stunningly fun and vibrant spin-off that captures classic 2D Zelda magic.",
    connectsTo: "None."
  }
];
